export const routes = {
  "/login": {
    title: "Login",
    pageTitle: "Login",
    breadcrumb: ["Login"],
    html: () => import("../pages/login/login.html?raw"),
    css: () => import("../pages/login/login.css"),
    js: () => import("../pages/login/login.js"),
    components: ['button', 'input'],
    layout: "blank",
  },
  "/recuperar-senha": {
    title: "Recuperar Senha",
    pageTitle: "Recuperar Senha",
    breadcrumb: ["Recuperar Senha"],
    html: () => import("../pages/recuperar-senha/recuperar-senha.html?raw"),
    css: () => import("../pages//recuperar-senha/recuperar-senha.css"),
    js: () => import("../pages/recuperar-senha/recuperar-senha.js"),
    components: ['button', 'input'],
    layout: "blank",
  },
  "/dashboard": {
    title: "Dashboard",
    pageTitle: "Painel",
    breadcrumb: ["Painel"],
    html: () => import("../pages/dashboard/dashboard.html?raw"),
    css: () => import("../pages/dashboard/dashboard.css"),
    js: () => import("../pages/dashboard/dashboard.js"),
    components: [],
    layout: "app",
  },
  "/cadastros": {
    title: "Pessoas e Empresas",
    pageTitle: "Pessoas e Empresas",
    breadcrumb: ["Painel", "Cadastros", "Pessoas e Empresas"],
    headerBreadcrumb: ["Painel", "Cadastros", "Pessoas e Empresas"],
    headerTabs: [
      { label: "Pessoas e Empresas", mode: "pessoas-empresas", active: true },
      { label: "Produtos e Serviços", mode: "produtos-servicos" },
    ],
    headerActiveTab: "Pessoas e Empresas",
    html: () => import("../pages/cadastros/cadCadastrosEmpresas.html?raw"),
    css: () => import("../pages/cadastros/cadCadastrosEmpresas.css"),
    js: () => import("../pages/cadastros/cadCadastrosEmpresas.js"),
    components: ["button", "input", "chip", "table", "pagination", "card", "toggle", "checkbox"],
    layout: "app",
  },
  "/cadastros/produtos-servicos": {
    title: "Pessoas e Empresas",
    pageTitle: "Pessoas e Empresas",
    breadcrumb: ["Painel", "Cadastros", "Pessoas e Empresas"],
    headerBreadcrumb: ["Painel", "Cadastros", "Pessoas e Empresas"],
    headerTabs: [
      { label: "Pessoas e Empresas", mode: "pessoas-empresas" },
      { label: "Produtos e Serviços", mode: "produtos-servicos", active: true },
    ],
    headerActiveTab: "Produtos e Serviços",
    html: () => import("../pages/cadastros/cadCadastrosEmpresas.html?raw"),
    css: () => import("../pages/cadastros/cadCadastrosEmpresas.css"),
    js: () => import("../pages/cadastros/cadCadastrosEmpresas.js"),
    components: ["button", "input", "chip", "table", "pagination", "card", "tabs", "toggle", "checkbox"],
    layout: "app",
  },
  "/cad-empresas-pessoas": {
    title: "Pessoas e Empresas",
    pageTitle: "Pessoas e Empresas",
    breadcrumb: ["Painel", "Cadastros", "Pessoas e Empresas"],
    headerBreadcrumb: ["Painel", "Cadastros", "Pessoas e Empresas"],
    html: () => import("../pages/cadastros/cadCadastrosEmpresas.html?raw"),
    css: () => import("../pages/cadastros/cadCadastrosEmpresas.css"),
    js: () => import("../pages/cadastros/cadCadastrosEmpresas.js"),
    components: ["button", "input", "chip", "table", "pagination", "card", "toggle", "checkbox"],
    layout: "app",
  },
  "/pedidos": {
    title: "Pedidos",
    pageTitle: "Pedidos",
    breadcrumb: ["Pedidos"],
    html: () => import("../pages/pedidos/pedidos.html?raw"),
    css: () => import("../pages/pedidos/pedidos.css"),
    js: () => import("../pages/pedidos/pedidos.js"),
    components: [],
    layout: "app",
  },
  "/producao": {
    title: "Produção",
    pageTitle: "Produção",
    breadcrumb: ["Produção"],
    html: () => import("../pages/producao/producao.html?raw"),
    css: () => import("../pages/producao/producao.css"),
    js: () => import("../pages/producao/producao.js"),
    components: [],
    layout: "app",
  },
  "/kanban-producao": {
    title: "Kanban de Produção",
    pageTitle: "Estufas",
    breadcrumb: ["Painel", "Estufas"],
    headerBreadcrumb: ["Painel", "Estufas"],
    headerTabs: [
      { label: "Agenda de Eventos" },
      { label: "Pedidos" },
      { label: "Produção", active: true },
      { label: "Expedição" },
      { label: "Operações" },
    ],
    headerActiveTab: "Produção",
    html: () => import("../pages/kanban/kanban.html?raw"),
    css: () => import("../pages/kanban/kanban.css"),
    js: () => import("../pages/kanban/kanban.js"),
    components: ['badge', 'button', 'chip', 'checkbox', 'toggle', 'input', 'tabs', 'drawer', 'kanban-column', 'kanban-card', 'color-picker'],
    layout: "app",
  },
  "/components/accordion": {
    title: "Accordion",
    pageTitle: "Accordion",
    breadcrumb: ["Componentes", "Accordion"],
    html: () => import("../pages/components/accordion.html?raw"),
    css: () => import("../pages/components/accordion.css"),
    js: () => import("../pages/components/accordion.js"),
    layout: "app",
  },
  "/components/avatar": {
    title: "Avatar",
    pageTitle: "Avatar",
    breadcrumb: ["Componentes", "Avatar"],
    html: () => import("../pages/components/avatar.html?raw"),
    css: () => import("../pages/components/avatar.css"),
    js: () => import("../pages/components/avatar.js"),
    layout: "app",
  },
  "/components/badge": {
    title: "Badge",
    pageTitle: "Badge",
    breadcrumb: ["Componentes", "Badge"],
    html: () => import("../pages/components/badge.html?raw"),
    css: () => import("../pages/components/badge.css"),
    js: () => import("../pages/components/badge.js"),
    layout: "app",
  },
  "/components/breadcrumb": {
    title: "Breadcrumb",
    pageTitle: "Breadcrumb",
    breadcrumb: ["Componentes", "Breadcrumb"],
    html: () => import("../pages/components/breadcrumb.html?raw"),
    css: () => import("../pages/components/breadcrumb.css"),
    js: () => import("../pages/components/breadcrumb.js"),
    layout: "app",
  },
  "/components/broadcast-banner": {
    title: "Broadcast Banner",
    pageTitle: "Broadcast Banner",
    breadcrumb: ["Componentes", "Broadcast Banner"],
    html: () => import("../pages/components/broadcast-banner.html?raw"),
    css: () => import("../pages/components/broadcast-banner.css"),
    js: () => import("../pages/components/broadcast-banner.js"),
    layout: "app",
  },
  "/components/button": {
    title: "Button",
    pageTitle: "Button",
    breadcrumb: ["Componentes", "Button"],
    html: () => import("../pages/components/button.html?raw"),
    css: () => import("../pages/components/button.css"),
    js: () => import("../pages/components/button.js"),
    layout: "app",
  },
  "/components/button-icon": {
    title: "Button Icon",
    pageTitle: "Button Icon",
    breadcrumb: ["Componentes", "Button Icon"],
    html: () => import("../pages/components/button-icon.html?raw"),
    css: () => import("../pages/components/button-icon.css"),
    js: () => import("../pages/components/button-icon.js"),
    layout: "app",
  },
  "/components/calendar": {
    title: "Calendar",
    pageTitle: "Calendar",
    breadcrumb: ["Componentes", "Calendar"],
    html: () => import("../pages/components/calendar.html?raw"),
    css: () => import("../pages/components/calendar.css"),
    js: () => import("../pages/components/calendar.js"),
    layout: "app",
  },
  "/components/card": {
    title: "Card",
    pageTitle: "Card",
    breadcrumb: ["Componentes", "Card"],
    html: () => import("../pages/components/card.html?raw"),
    css: () => import("../pages/components/card.css"),
    js: () => import("../pages/components/card.js"),
    layout: "app",
  },
  "/components/checkbox": {
    title: "Checkbox",
    pageTitle: "Checkbox",
    breadcrumb: ["Componentes", "Checkbox"],
    html: () => import("../pages/components/checkbox.html?raw"),
    css: () => import("../pages/components/checkbox.css"),
    js: () => import("../pages/components/checkbox.js"),
    layout: "app",
  },
  "/components/chip": {
    title: "Chip",
    pageTitle: "Chip",
    breadcrumb: ["Componentes", "Chip"],
    html: () => import("../pages/components/chip.html?raw"),
    css: () => import("../pages/components/chip.css"),
    js: () => import("../pages/components/chip.js"),
    layout: "app",
  },
  "/components/divider": {
    title: "Divider",
    pageTitle: "Divider",
    breadcrumb: ["Componentes", "Divider"],
    html: () => import("../pages/components/divider.html?raw"),
    css: () => import("../pages/components/divider.css"),
    js: () => import("../pages/components/divider.js"),
    layout: "app",
  },
  "/components/dropdown": {
    title: "Dropdown Menu",
    pageTitle: "Dropdown Menu",
    breadcrumb: ["Componentes", "Dropdown Menu"],
    html: () => import("../pages/components/dropdown.html?raw"),
    css: () => import("../pages/components/dropdown.css"),
    js: () => import("../pages/components/dropdown.js"),
    layout: "app",
  },
  "/components/input": {
    title: "Input",
    pageTitle: "Input",
    breadcrumb: ["Componentes", "Input"],
    html: () => import("../pages/components/input.html?raw"),
    css: () => import("../pages/components/input.css"),
    js: () => import("../pages/components/input.js"),
    layout: "app",
  },
  "/components/link": {
    title: "Link",
    pageTitle: "Link",
    breadcrumb: ["Componentes", "Link"],
    html: () => import("../pages/components/link.html?raw"),
    css: () => import("../pages/components/link.css"),
    js: () => import("../pages/components/link.js"),
    layout: "app",
  },
  "/components/modal": {
    title: "Modal",
    pageTitle: "Modal",
    breadcrumb: ["Componentes", "Modal"],
    html: () => import("../pages/components/modal.html?raw"),
    css: () => import("../pages/components/modal.css"),
    js: () => import("../pages/components/modal.js"),
    layout: "app",
  },
  "/components/pagination": {
    title: "Pagination",
    pageTitle: "Pagination",
    breadcrumb: ["Componentes", "Pagination"],
    html: () => import("../pages/components/pagination.html?raw"),
    css: () => import("../pages/components/pagination.css"),
    js: () => import("../pages/components/pagination.js"),
    layout: "app",
  },
  "/components/progress": {
    title: "Progress",
    pageTitle: "Progress",
    breadcrumb: ["Componentes", "Progress"],
    html: () => import("../pages/components/progress.html?raw"),
    css: () => import("../pages/components/progress.css"),
    js: () => import("../pages/components/progress.js"),
    layout: "app",
  },
  "/components/radio": {
    title: "Radio Button",
    pageTitle: "Radio Button",
    breadcrumb: ["Componentes", "Radio Button"],
    html: () => import("../pages/components/radio.html?raw"),
    css: () => import("../pages/components/radio.css"),
    js: () => import("../pages/components/radio.js"),
    layout: "app",
  },
  "/components/sidenav": {
    title: "Side Navigation",
    pageTitle: "Side Navigation",
    breadcrumb: ["Componentes", "Side Navigation"],
    html: () => import("../pages/components/sidenav.html?raw"),
    css: () => import("../pages/components/sidenav.css"),
    js: () => import("../pages/components/sidenav.js"),
    layout: "app",
  },
  "/components/navbar": {
    title: "Navigation Bar",
    pageTitle: "Navigation Bar",
    breadcrumb: ["Componentes", "Navigation Bar"],
    html: () => import("../pages/components/navbar.html?raw"),
    css: () => import("../pages/components/navbar.css"),
    js: () => import("../pages/components/navbar.js"),
    layout: "app",
  },
  "/components/slider": {
    title: "Slider",
    pageTitle: "Slider",
    breadcrumb: ["Componentes", "Slider"],
    html: () => import("../pages/components/slider.html?raw"),
    css: () => import("../pages/components/slider.css"),
    js: () => import("../pages/components/slider.js"),
    layout: "app",
  },
  "/components/status": {
    title: "Status",
    pageTitle: "Status",
    breadcrumb: ["Componentes", "Status"],
    html: () => import("../pages/components/status.html?raw"),
    css: () => import("../pages/components/status.css"),
    js: () => import("../pages/components/status.js"),
    layout: "app",
  },
  "/components/stepper": {
    title: "Stepper",
    pageTitle: "Stepper",
    breadcrumb: ["Componentes", "Stepper"],
    html: () => import("../pages/components/stepper.html?raw"),
    css: () => import("../pages/components/stepper.css"),
    js: () => import("../pages/components/stepper.js"),
    layout: "app",
  },
  "/components/toggle": {
    title: "Toggle",
    pageTitle: "Toggle",
    breadcrumb: ["Componentes", "Toggle"],
    html: () => import("../pages/components/toggle.html?raw"),
    css: () => import("../pages/components/toggle.css"),
    js: () => import("../pages/components/toggle.js"),
    layout: "app",
  },
  "/components/tabs": {
    title: "Tabs",
    pageTitle: "Tabs",
    breadcrumb: ["Componentes", "Tabs"],
    html: () => import("../pages/components/tabs.html?raw"),
    css: () => import("../pages/components/tabs.css"),
    js: () => import("../pages/components/tabs.js"),
    layout: "app",
  },
  "/components/table": {
    title: "Data Display",
    pageTitle: "Data Display",
    breadcrumb: ["Componentes", "Data Display"],
    html: () => import("../pages/components/table.html?raw"),
    css: () => import("../pages/components/table.css"),
    js: () => import("../pages/components/table.js"),
    layout: "app",
  },
  "/components/toast": {
    title: "Toast",
    pageTitle: "Toast",
    breadcrumb: ["Componentes", "Toast"],
    html: () => import("../pages/components/toast.html?raw"),
    css: () => import("../pages/components/toast.css"),
    js: () => import("../pages/components/toast.js"),
    layout: "app",
  },
  "/components/tooltip": {
    title: "Tooltip",
    pageTitle: "Tooltip",
    breadcrumb: ["Componentes", "Tooltip"],
    html: () => import("../pages/components/tooltip.html?raw"),
    css: () => import("../pages/components/tooltip.css"),
    js: () => import("../pages/components/tooltip.js"),
    layout: "app",
  },
  "/components/file-upload": {
    title: "File Upload",
    pageTitle: "File Upload",
    breadcrumb: ["Componentes", "File Upload"],
    html: () => import("../pages/components/file-upload.html?raw"),
    css: () => import("../pages/components/file-upload.css"),
    js: () => import("../pages/components/file-upload.js"),
    layout: "app",
  },
  "/icons": {
    title: "Icons",
    pageTitle: "Ícones",
    breadcrumb: ["Ícones"],
    html: () => import("../pages/icons/icons.html?raw"),
    css: () => import("../pages/icons/icons.css"),
    js: () => import("../pages/icons/icons.js"),
    layout: "app",
  },
};
